### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx-multi.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# docker build -f Dockerfile-multi -t localhost:32000/brainupgrade/global-bank-frontend:1.0.0 -t brainupgrade/global-bank-frontend:1.0.0 . && docker push brainupgrade/global-bank-frontend:1.0.0 && docker push localhost:32000/brainupgrade/global-bank-frontend:1.0.0
